import { mkdirSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, isAbsolute, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseArgs } from 'node:util'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const defaults = {
  plugin: resolve(root, 'release/feishu-long-connection/dist/index.mjs'),
  out: resolve(root, 'release/profiles/desktop.patch.yml'),
}
const { values } = parseArgs({
  options: {
    plugin: { type: 'string' },
    out: { type: 'string' },
    workspace: { type: 'string' },
    botName: { type: 'string', default: 'ToneClaw' },
  },
})

const pluginPath = resolve(values.plugin ?? defaults.plugin)
const outputPath = resolve(values.out ?? defaults.out)
const workspacePath = resolve(values.workspace ?? join(homedir(), '.dsh', 'workspaces', 'toneclaw'))
if (!isAbsolute(pluginPath)) throw new Error('--plugin must be absolute after resolution')

const pluginReference = relative(dirname(outputPath), pluginPath).replaceAll('\\', '/')
const patch = `# Generated by toneclaw-product; do not put developer checkout paths here.
- insert:
    - id: webhook-runtime
      name: '@deepseek-ai/dsh-webhook'

    - id: feishu-long-connection
      name: '${pluginReference}'
      config:
        source: primary-feishu
        appIdEnv: DSH_FEISHU_APP_ID
        appSecretEnv: DSH_FEISHU_APP_SECRET
        loggerLevel: info
        consoleArrival: true

    - id: feishu-channel
      name: '@deepseek-ai/dsh-webhook-feishu'
      config:
        source: primary-feishu
        appIdEnv: DSH_FEISHU_APP_ID
        appSecretEnv: DSH_FEISHU_APP_SECRET
        workspacePath: '${workspacePath.replaceAll('\\', '/')}'
        agentPreset: standard
        permissionPreset: read-only
        botName: '${values.botName}'
`

mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, patch, 'utf8')
console.log(`profile: ${outputPath}`)
console.log(`plugin:  ${pluginReference}`)
